import { Region } from "./types";

// Regions, from https://github.com/olahol/iso-3166-2.js/blob/master/data.csv
export const regions: Region[] = [
  {country: "Poland", code: "PL-DS", name: "Dolnośląskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-KP", name: "Kujawsko-pomorskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-LB", name: "Lubuskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-LD", name: "Łódzkie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-LU", name: "Lubelskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-MA", name: "Małopolskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-MZ", name: "Mazowieckie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-OP", name: "Opolskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-PD", name: "Podlaskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-PK", name: "Podkarpackie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-PM", name: "Pomorskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-SK", name: "Świętokrzyskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-SL", name: "Śląskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-WN", name: "Warmińsko-mazurskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-WP", name: "Wielkopolskie",	type: "Province", countryCode: "PL"},
  {country: "Poland", code: "PL-ZP", name: "Zachodniopomorskie",	type: "Province", countryCode: "PL"},
  {country: "Romania", code: "RO-AB", name: "Alba",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-AG", name: "Argeş",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-AR", name: "Arad",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-B", name: "Bucureşti",	type: "Municipality", countryCode: "RO"},
  {country: "Romania", code: "RO-BC", name: "Bacău",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BH", name: "Bihor",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BN", name: "Bistriţa-Năsăud",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BR", name: "Brăila",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BT", name: "Botoşani",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BV", name: "Braşov",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-BZ", name: "Buzău",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-CJ", name: "Cluj",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-CL", name: "Călăraşi",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-CS", name: "Caraş-Severin",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-CT", name: "Constanţa",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-CV", name: "Covasna",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-DB", name: "Dâmboviţa",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-DJ", name: "Dolj",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-GJ", name: "Gorj",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-GL", name: "Galaţi",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-GR", name: "Giurgiu",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-HD", name: "Hunedoara",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-HR", name: "Harghita",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-IF", name: "Ilfov",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-IL", name: "Ialomiţa",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-IS", name: "Iaşi",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-MH", name: "Mehedinţi",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-MM", name: "Maramureş",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-MS", name: "Mureş",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-NT", name: "Neamţ",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-OT", name: "Olt",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-PH", name: "Prahova",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-SB", name: "Sibiu",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-SJ", name: "Sălaj",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-SM", name: "Satu Mare",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-SV", name: "Suceava",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-TL", name: "Tulcea",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-TM", name: "Timiş",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-TR", name: "Teleorman",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-VL", name: "Vâlcea",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-VN", name: "Vrancea",	type: "Department", countryCode: "RO"},
  {country: "Romania", code: "RO-VS", name: "Vaslui",	type: "Department", countryCode: "RO"},
  {country: "Moldova", code: "MD-AN", name: "Anenii Noi",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-BA", name: "Bălţi",	type: "City", countryCode: "MD"},
  {country: "Moldova", code: "MD-BD", name: "Bender",	type: "City", countryCode: "MD"},
  {country: "Moldova", code: "MD-BR", name: "Briceni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-BS", name: "Basarabeasca",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CA", name: "Cahul",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CL", name: "Călăraşi",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CM", name: "Cimişlia",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CR", name: "Criuleni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CS", name: "Căuşeni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CT", name: "Cantemir",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-CU", name: "Chişinău",	type: "City", countryCode: "MD"},
  {country: "Moldova", code: "MD-DO", name: "Donduşeni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-DR", name: "Drochia",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-DU", name: "Dubăsari",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-ED", name: "Edineţ",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-FA", name: "Făleşti",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-FL", name: "Floreşti",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-GA", name: "Găgăuzia, Unitatea teritorială autonomă	Autonomous territorial", type: "unit", countryCode: "MD"},
  {country: "Moldova", code: "MD-GL", name: "Glodeni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-HI", name: "Hînceşti",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-IA", name: "Ialoveni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-LE", name: "Leova",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-NI", name: "Nisporeni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-OC", name: "Ocniţa",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-OR", name: "Orhei",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-RE", name: "Rezina",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-RI", name: "Rîşcani",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-SD", name: "Şoldăneşti",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-SI", name: "Sîngerei",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-SN", name: "Stînga Nistrului, unitatea teritorială din	Territorial", type: "unit", countryCode: "MD"},
  {country: "Moldova", code: "MD-SO", name: "Soroca",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-ST", name: "Străşeni",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-SV", name: "Ştefan Vodă",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-TA", name: "Taraclia",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-TE", name: "Teleneşti",	type: "District", countryCode: "MD"},
  {country: "Moldova", code: "MD-UN", name: "Ungheni",	type: "District", countryCode: "MD"},
  {country: "Hungary", code: "HU-BA", name: "Baranya",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-BC", name: "Békéscsaba", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-BE", name: "Békés",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-BK", name: "Bács-Kiskun",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-BU", name: "Budapest	Capital", type: "city", countryCode: "HU"},
  {country: "Hungary", code: "HU-BZ", name: "Borsod-Abaúj-Zemplén",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-CS", name: "Csongrád",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-DE", name: "Debrecen", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-DU", name: "Dunaújváros", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-EG", name: "Eger", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-ER", name: "Érd", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-FE", name: "Fejér",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-GS", name: "Győr-Moson-Sopron",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-GY", name: "Győr", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-HB", name: "Hajdú-Bihar",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-HE", name: "Heves",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-HV", name: "Hódmezővásárhely", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-JN", name: "Jász-Nagykun-Szolnok",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-KE", name: "Komárom-Esztergom",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-KM", name: "Kecskemét", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-KV", name: "Kaposvár", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-MI", name: "Miskolc", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-NK", name: "Nagykanizsa", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-NO", name: "Nógrád",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-NY", name: "Nyíregyháza", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-PE", name: "Pest",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-PS", name: "Pécs", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SD", name: "Szeged", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SF", name: "Székesfehérvár", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SH", name: "Szombathely", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SK", name: "Szolnok", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SN", name: "Sopron", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SO", name: "Somogy",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-SS", name: "Szekszárd", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-ST", name: "Salgótarján", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-SZ", name: "Szabolcs-Szatmár-Bereg",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-TB", name: "Tatabánya", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-TO", name: "Tolna",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-VA", name: "Vas",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-VE", name: "Veszprém",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-VM", name: "Veszprém", type: "City of county right", countryCode: "HU"},
  {country: "Hungary", code: "HU-ZA", name: "Zala",	type: "County", countryCode: "HU"},
  {country: "Hungary", code: "HU-ZE", name: "Zalaegerszeg", type: "City of county right", countryCode: "HU"},
]